services:

  frontend:
    image: node:23-alpine3.20
    working_dir: frontend/
    env_file:
      - frontend/.env
    ports:
      - ${WEB_PORT}:3000
    volumes:
      - ./frontend:/frontend:delegated
    command: sh -c "npm install && npm run build && node /frontend/.output/server/index.mjs"
    depends_on:
      - backend
    restart: always
  
  backend:
    build: 
      context: .
      args:
        ENV_TYPE: ${APP_ENV}
    env_file:
      - backend/.env
    volumes:
      - ./:/backend
    ports:
      - ${API_PORT}:5000
    deploy:
      resources:
        limits:
          cpus: '1'  # Use up to 50% of a single CPU core
          memory: '1024M'  # Use up to 1024M of memory
    depends_on:
      - database
    restart: always

  database:
    image: postgres:17
    container_name: database
    env_file:
      - backend/.env
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - ./DB_DATA:/var/lib/postgresql/data
    ports:
      - ${POSTGRES_PORT}:5432
    restart: always
